export const Main = (props) => {
	const paragraphs = props.paragraphs || [
		"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quamquam ex omnibus philosophis Stoici plurima novaverunt, Zenoque, eorum princeps, non tam rerum inventor fuit quam verborum novorum. Cur ad reliquos Pythagoreos, Echecratem, Timaeum, Arionem, Locros, ut, cum Socratem expressisset, adiungeret Pythagoreorum disciplinam eaque, quae Socrates repudiabat, addisceret? Lege laudationes, Torquate, non eorum, qui sunt ab Homero laudati, non Cyri, non Agesilai, non Aristidi aut Themistocli, non Philippi aut Alexandri, lege nostrorum hominum, lege vestrae familiae; Praeterea et appetendi et refugiendi et omnino rerum gerendarum initia proficiscuntur aut a voluptate aut a dolore. Perspicuum est enim, nisi aequitas, fides, iustitia proficiscantur a natura, et si omnia haec ad utilitatem referantur, virum bonum non posse reperiri; Corporis igitur nostri partes totaque figura et forma et statura quam apta ad naturam sit, apparet, neque est dubium, quin frons, oculi, aures et reliquae partes quales propriae sint hominis intellegatur. Ex quo intellegi debet homini id esse in bonis ultimum, secundum naturam vivere, quod ita interpretemur: vivere ex hominis natura undique perfecta et nihil requirente. Cum efficere non possit ut cuiquam, qui ipse sibi notus sit, hoc est qui suam naturam sensumque perspexerit, vacuitas doloris et voluptas idem esse videatur. Duo Reges: constructio interrete. Sed in ceteris artibus cum dicitur artificiose, posterum quodam modo et consequens putandum est, quod illi §pigennhmatikÒn appellant; Pompeius in foedere Numantino infitiando fuit, nec vero omnia timente, sed primum qui animi conscientiam non curet, quam scilicet comprimere nihil est negotii. Aderamus nos quidem adolescentes, sed multi amplissimi viri, quorum nemo censuit plus Fadiae dandum, quam posset ad eam lege Voconia pervenire. Nam si +omnino nos+ neglegemus, in Aristonea vitia incidemus et peccata obliviscemurque quae virtuti ipsi principia dederimus; Cum enim virtutis hoc proprium sit, earum rerum, quae secundum naturam sint, habere delectum, qui omnia sic exaequaverunt, ut in utramque partem ita paria redderent, uti nulla selectione uterentur, hi virtutem ipsam sustulerunt. Nam et ille apud Trabeam voluptatem animi nimiam laetitiam dicit eandem, quam ille Caecilianus, qui omnibus laetitiis laetum esse se narrat. Hoc autem tempore, etsi multa in omni parte Athenarum sunt in ipsis locis indicia summorum virorum, tamen ego illa moveor exhedra.",
		"Quae dici eadem de ceteris virtutibus possunt, quarum omnium fundamenta vos in voluptate tamquam in aqua ponitis. Habebat tamen rationem valitudinis: utebatur iis exercitationibus, ut ad cenam et sitiens et esuriens veniret, eo cibo, qui et suavissimus esset et idem facillimus ad concoquendum, vino et ad voluptatem et ne noceret. Restat locus huic disputationi vel maxime necessarius de amicitia, quam, si voluptas summum sit bonum, affirmatis nullam omnino fore. Lege laudationes, Torquate, non eorum, qui sunt ab Homero laudati, non Cyri, non Agesilai, non Aristidi aut Themistocli, non Philippi aut Alexandri, lege nostrorum hominum, lege vestrae familiae; Id enim ille summum bonum eu)qumi/an et saepe a)qambi/an appellat, id est animum terrore liberum. In primo enim ortu inest teneritas ac mollitia quaedam, ut nec res videre optimas nec agere possint. Atqui si, ut convenire debet inter nos, est quaedam appetitio naturalis ea, quae secundum naturam sunt, appetens, eorum omnium est aliquae summa facienda. Sic igitur in homine perfectio ista in eo potissimum, quod est optimum, id est in virtute, laudatur.",
		"Illud mihi a te nimium festinanter dictum videtur, sapientis omnis esse semper beatos; Si enim ad honestatem omnia referant neque in ea voluptatem dicant inesse, ait eos voce inani sonarehis enim ipsis verbis utitur-neque intellegere nec videre sub hanc vocem honestatis quae sit subicienda sententia. Nec tamen argumentum hoc Epicurus a parvis petivit aut etiam a bestiis, quae putat esse specula naturae, ut diceret ab iis duce natura hanc voluptatem expeti nihil dolendi. Nam quicquid quaeritur, id habet aut generis ipsius sine personis temporibusque aut his adiunctis facti aut iuris aut nominis controversiam. Ius autem, quod ita dici appellarique possit, id esse natura, alienumque esse a sapiente non modo iniuriam cui facere, verum etiam nocere. Quodsi esset in voluptate summum bonum, ut dicitis, optabile esset maxima in voluptate nullo intervallo interiecto dies noctesque versari, cum omnes sensus dulcedine omni quasi perfusi moverentur. Sed emolumenta communia esse dicuntur, recte autem facta et peccata non habentur communia. Quid autem sit, quod ita moveat itaque a natura in primo ortu appetatur, non constat deque eo est inter philosophos, cum summum bonum exquiritur, omnis dissensio.",
		"An id exploratum cuiquam potest esse, quo modo se hoc habiturum sit corpus, non dico ad annum, sed ad vesperum? Alteri negant quicquam esse bonum, nisi quod honestum sit, alteri plurimum se et longe longeque plurimum tribuere honestati, sed tamen et in corpore et extra esse quaedam bona. Nam illud quidem adduci vix possum, ut ea, quae senserit ille, tibi non vera videantur. Illud quaero, quid ei, qui in voluptate summum bonum ponat, consentaneum sit dicere. Praeterea sublata cognitione et scientia tollitur omnis ratio et vitae degendae et rerum gerendarum. Qui mos cum a posterioribus non esset retentus, Arcesilas eum revocavit instituitque ut ii, qui se audire vellent, non de se quaererent, sed ipsi dicerent, quid sentirent; Nam, ut saepe iam dixi, in infirma aetate inbecillaque mente vis naturae quasi per caliginem cernitur; Dicis eadem omnia et bona et mala, quae quidem dicunt ii, qui numquam philosophum pictum, ut dicitur, viderunt: valitudinem, vires, staturam, formam, integritatem unguiculorum omnium bona, deformitatem, morbum, debilitatem mala. Quamquam ego non quaero, quid tibi a me probatum sit, sed huic Ciceroni nostro, quem discipulum cupio a te abducere. Sin ea non neglegemus neque tamen ad finem summi boni referemus, non multum ab Erilli levitate aberrabimus. Illi igitur antiqui non tam acute optabiliorem illam vitam putant, praestantiorem, beatiorem, Stoici autem tantum modo praeponendam in seligendo, non quo beatior ea vita sit, sed quod ad naturam accommodatior. Et ego: Tu vero, inquam, Piso, ut saepe alias, sic hodie ita nosse ista visus es, ut, si tui nobis potestas saepius fieret, non multum Graecis supplicandum putarem. Ita fit, ut duo genera propter se expetendorum reperiantur, unum, quod est in iis, in quibus completar illud extremum, quae sunt aut animi aut corporis; Hic si Peripateticus fuisset, permansisset, credo, in sententia, qui dolorem malum dicunt esse, de asperitate autem eius fortiter ferenda praecipiunt eadem, quae Stoici.",
		"Dicis eadem omnia et bona et mala, quae quidem dicunt ii, qui numquam philosophum pictum, ut dicitur, viderunt: valitudinem, vires, staturam, formam, integritatem unguiculorum omnium bona, deformitatem, morbum, debilitatem mala. Ergo ita: non posse honeste vivi, nisi honeste vivatur? Si enim Zenoni licuit, cum rem aliquam invenisset inusitatam, inauditum quoque ei rei nomen inponere, cur non liceat Catoni? Cenasti in vita numquam bene, cum omnia in ista Consumis squilla atque acupensere cum decimano. Quae mihi ipsi, qui volo et esse et haberi gratus, grata non essent, nisi eum perspicerem mea causa mihi amicum fuisse, non sua, nisi hoc dicis sua, quod interest omnium recte facere. Hic Speusippus, hic Xenocrates, hic eius auditor Polemo, cuius illa ipsa sessio fuit, quam videmus. Ut enim qui mortem in malis ponit non potest eam non timere, sic nemo ulla in re potest id, quod malum esse decreverit, non curare idque contemnere. Quae cum ita sint, effectum est nihil esse malum, quod turpe non sit. Fadio Gallo, cuius in testamento scriptum esset se ab eo rogatum ut omnis hereditas ad filiam perveniret. Qui autem de summo bono dissentit de tota philosophiae ratione dissentit. Cum autem paulum firmitatis accessit, et animo utuntur et sensibus conitunturque, ut sese erigant, et manibus utuntur et eos agnoscunt, a quibus educantur. Alia quaedam dicent, credo, magna antiquorum esse peccata, quae ille veri investigandi cupidus nullo modo ferre potuerit.",
	];

	return (
		<main style={{ flex: "2" }}>
			{paragraphs.map((item, index) => {
				return <p key={index}>{item}</p>;
			})}
		</main>
	);
};
